KTech.VirtualStore.Web/Controllers/CarrinhoController.cs
using KTech.VirtualStore.Domain.Entities;
using KTech.VirtualStore.Domain.Repository;
using KTech.VirtualStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTech.VirtualStore.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepository _repositorio;

        public ViewResult Index(Carrinho carrinho, string returnUrl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = carrinho,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Resumo(Carrinho carrinho)
        {
            return PartialView(carrinho);
        }

        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }

        [HttpPost]
        public ViewResult FecharPedido(Carrinho carrinho, Pedido pedido)
        {
            EmailConfiguracoes email = new EmailConfiguracoes
            {
                EscreverArquivo = bool.Parse(ConfigurationManager.AppSettings["Email.EscreverArquivo"] ?? "false")
            };

            EmailPedido emailPedido = new EmailPedido(email);

            if (!carrinho.ItensCarrinho.Any())
            {
                ModelState.AddModelError("", "Não foi possível concluir o pedido, seu carrinho está vazio!");
            }

            if (ModelState.IsValid)
            {
                emailPedido.ProcessarPedido(carrinho, pedido);
                carrinho.LimparCarrinho();
                return View("PedidoConcluido");
            }
            else
            {
                return View(pedido);
            }
        }

        public RedirectToRouteResult Adicionar(Carrinho carrinho, int produtoId, int quantidade, string returnUrl)
        {
            _repositorio = new ProdutosRepository();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                carrinho.AdicionarItem(produto, quantidade);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult Remover(Carrinho carrinho, int produtoId, string returnUrl)
        {
            _repositorio = new ProdutosRepository();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                carrinho.RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult PedidoConcluido()
        {
            return View();
        }
    }
}

KTech.VirtualStore.Web/Controllers/CategoriaController.cs
using KTech.VirtualStore.Domain.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTech.VirtualStore.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutosRepository _repositorio;

        // GET: Categoria
        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            _repositorio = new ProdutosRepository();

            IEnumerable<string> categorias = _repositorio.Produtos
                .Select(c => c.Categoria)
                .Distinct()
                .OrderBy(c => c);

            return PartialView(categorias);
        }
    }
}

KTech.VirtualStore.Web/Controllers/VitrineController.cs
using KTech.VirtualStore.Domain.Entities;
using KTech.VirtualStore.Domain.Repository;
using KTech.VirtualStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTech.VirtualStore.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepository _repositorio;
        public int ProdutosPorPagina = 5;

        // GET: Vitrine
        //public ViewResult ListaProdutos(string categoria, int pagina = 1)
        //{
        //    _repositorio = new ProdutosRepository();
        //    ProdutosViewModel model = new ProdutosViewModel
        //    {

        //        Produtos = _repositorio.Produtos
        //        .Where(p => categoria == null || p.Categoria == categoria)
        //        .OrderBy(p => p.Nome)
        //        .Skip((pagina - 1) * ProdutosPorPagina)
        //        .Take(ProdutosPorPagina),

        //        Paginacao = new Paginacao
        //        {
        //            PaginaAtual = pagina,
        //            ItensPorPagina = ProdutosPorPagina,
        //            ItensTotal = categoria == null ? _repositorio.Produtos.Count() : _repositorio.Produtos.Where(p => categoria == null || p.Categoria == categoria).Count()
        //        },

        //        CategoriaAtual = categoria
        //    };

        //    return View(model);
        //}

        [Route("DetalhesProduto/{id}/{produto}")]
        public ViewResult Detalhes(int id)
        {
            _repositorio = new ProdutosRepository();
            Produto produto = _repositorio.ObterProduto(id);
            return View(produto);
        }

        public ViewResult ListaProdutos(string categoria)
        {
            _repositorio = new ProdutosRepository();

            var model = new ProdutosViewModel();

            var rnd = new Random();

            if (categoria != null)
            {
                model.Produtos = _repositorio.Produtos
                    .Where(p => p.Categoria == categoria)
                    .OrderBy(x => rnd.Next()).ToList();
            }
            else
            {
                model.Produtos = _repositorio.Produtos
                    .OrderBy(x => rnd.Next())
                    .Take(ProdutosPorPagina).ToList();
            }

            return View(model);
        }

        [Route("Vitrine/Produto/ObterImagem/{produtoId}")]
        public FileContentResult ObterImagem(int produtoId)
        {
            _repositorio = new ProdutosRepository();
            Produto prod = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (prod != null)
            {
                return File(prod.Imagem, prod.ImagemMimeType);
            }
            return null;
        }
    }
}

KTech.VirtualStore.Web/Views/Shared/ProdutoDetalhes.cshtml
@model KTech.VirtualStore.Domain.Entities.Produto
@using KTech.VirtualStore.Web.HtmlHelpers

<div class="well">

    @if (Model.Imagem != null)
    {
        <div class="row">
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" style="width:120px;height:120px;" src="@Url.Action("ObterImagem", "Vitrine", new { Model.ProdutoId })" />
            </div>
        </div>
    }

    <div class="row">
        <h4>
            @Html.ActionLink(Model.Nome, "Detalhes", "Vitrine", new { id = Model.ProdutoId, produto = Model.Nome.ToSeoUrl() }, new { @class = "deco-none" })
            <br />
            <span class="pull-right label label-primary">
                @Model.Preco.ToString("c")
            </span>
        </h4>
    </div>

</div>

KTech.VirtualStore.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KTech Loja Virtual</title>

    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="~/Content/ErroEstilo.css" rel="stylesheet" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@

    @Styles.Render("~/Content/css")

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <a class="navbar-brand" href="#">KTech Loja Virtual - Seu esporte é aqui</a>

        @Html.Action("Resumo", "Carrinho")
    </div>

    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu", "Categoria")
        </div>

        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @* para renderizar o jquery primeiro *@
    @RenderSection("scripts", required: false)

</body>
</html>